#language: node_js
sudo: required
services:
    - docker
before_install:
    - docker build -t lemore/react-test -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true lemore/react-test npm run test
after_success:
    - docker build -t lemore/multi-client ./client
    - docker build -t lemore/multi-nginx ./nginx
    - docker build -t lemore/multi-server ./server
    - docker build -t lemore/multi-worker ./worker
    # login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #load images to docker hub
    - docker push lemore/multi-client
    - docker push lemore/multi-nginx
    - docker push lemore/multi-server
    - docker push lemore/multi-worker
